nelmio_api_doc:
  documentation:
    servers:
      - url: http://localhost:8000/
        description: API Address
    info:
      title: CRM System
      description: CRM API!
      version: 1.0.0
    components:
      securitySchemes:
        Bearer:
          type: http
          scheme: bearer
          bearerFormat: JWT
    security:
      - Bearer: [ ]
  areas:
    path_patterns:
      - ^/api/public/(?!/doc$)