# See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/6.x/configuration.html
scheb_two_factor:
    email:
        enabled: true
        digits: 6
        sender_email: authentication@noreply.com
        sender_name: CRM Auth
        mailer: App\Security\TwoFactorCodeMailer
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
